apiRules:
- include:
    uidRegex: ^nickmaltbie\.IntoTheRoots
    type: Namespace
- include:
    uidRegex: ^nickmaltbie\.IntoTheRoots\.*
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace